package com.powerinspection.agent.domain;

public final class AgentEnums {
  private AgentEnums() {
  }

  public enum CaseStatus { OPEN, ANALYZING, WAITING_HUMAN, WAITING_APPROVAL, ACTION_EXECUTING, RESOLVED, FAILED, CLOSED }
  public enum RunStatus { QUEUED, RUNNING, WAITING_TOOL, WAITING_HUMAN, WAITING_APPROVAL, SUCCEEDED, FAILED, CANCELLED, TIMED_OUT, STEP_LIMIT_REACHED }
  public enum StepType { RUN_STARTED, TOOL_CALL_REQUESTED, TOOL_CALL_STARTED, TOOL_CALL_SUCCEEDED, TOOL_CALL_FAILED, EVIDENCE_ADDED, LLM_ANALYZED, ACTION_PROPOSED, ACTION_APPROVED, ACTION_REJECTED, ACTION_STARTED, ACTION_SUCCEEDED, ACTION_FAILED, RUN_FINISHED, RUN_FAILED }
  public enum ToolCallStatus { REQUESTED, RUNNING, SUCCEEDED, FAILED, TIMED_OUT, CANCELLED }
  public enum EvidenceSourceType { TASK, ALARM, WORK_ORDER, VISION_RESULT, OPERATOR_INPUT, LLM_FALLBACK }
  public enum ActionType { CREATE_WORK_ORDER_DRAFT, PUSH_NOTIFICATION, ACKNOWLEDGE_ALARM, REQUEST_TASK_PAUSE, CANCEL_TASK, ROBOT_MANUAL_CONTROL }
  public enum ActionStatus { PROPOSED, APPROVED, REJECTED, EXECUTING, SUCCEEDED, FAILED, EXPIRED, CANCELLED }
  public enum RiskLevel { LOW, MEDIUM, HIGH, CRITICAL }
  public enum PolicyDecisionType { AUTO_EXECUTE, REQUIRE_APPROVAL, DENY }
  public enum ExecutionClaimStatus { EXECUTING, SUCCEEDED, FAILED }
}
