package com.powerinspection.agent.domain;

public final class AgentEnums {
  private AgentEnums() {
  }

  public enum CaseStatus { OPEN, ANALYZING, WAITING_HUMAN, WAITING_APPROVAL, ACTION_EXECUTING, RESOLVED, FAILED, CLOSED }
  public enum RunStatus { QUEUED, RUNNING, WAITING_TOOL, WAITING_HUMAN, WAITING_APPROVAL, ACTION_EXECUTING, SUCCEEDED, FAILED, CANCELLED, TIMED_OUT, STEP_LIMIT_REACHED }
  public enum StepType { RUN_STARTED, PLAN_CREATED, TOOL_CALL_REQUESTED, TOOL_CALL_STARTED, TOOL_CALL_SUCCEEDED, TOOL_CALL_FAILED, EVIDENCE_ADDED, HUMAN_INPUT_REQUESTED, HUMAN_INPUT_RECEIVED, LLM_ANALYZED, ACTION_PROPOSED, ACTION_APPROVED, ACTION_REJECTED, ACTION_STARTED, ACTION_SUCCEEDED, ACTION_FAILED, RUN_FINISHED, RUN_FAILED }
  public enum ToolCallStatus { REQUESTED, RUNNING, SUCCEEDED, FAILED, TIMED_OUT, CANCELLED }
  public enum EvidenceSourceType { TASK, TASK_EVENT, ALARM, WORK_ORDER, ROBOT, ROUTE, VISION_RESULT, OPERATOR_INPUT, LLM_FALLBACK }
  public enum ActionType { PUSH_NOTIFICATION_TO_SELF, CREATE_WORK_ORDER_DRAFT, ACKNOWLEDGE_ALARM, REQUEST_TASK_PAUSE, ROBOT_MANUAL_CONTROL, CANCEL_TASK, MODIFY_USER_PERMISSION, MODIFY_MODEL_CONFIGURATION, EXECUTE_ARBITRARY_HTTP_REQUEST, EXECUTE_COMMAND, READ_LOCAL_FILE, PUSH_NOTIFICATION }
  public enum ActionStatus { PROPOSED, APPROVED, REJECTED, EXECUTING, SUCCEEDED, FAILED, EXPIRED, CANCELLED }
  public enum RiskLevel { LOW, MEDIUM, HIGH, CRITICAL }
  public enum PolicyDecisionType { AUTO_EXECUTE, REQUIRE_APPROVAL, DENY }
  public enum HumanInputMode { ANSWER, CONTINUE_WITH_CURRENT_EVIDENCE, CANCEL_RUN }
  public enum HumanQuestionStatus { OPEN, ANSWERED, CANCELLED }
  public enum ExecutionClaimStatus { EXECUTING, SUCCEEDED, FAILED }
}
